FROM mcr.microsoft.com/devcontainers/python:1-3.10-bullseye
#COPY requirements.txt /tmp/requirements.txt
#RUN pip3 install --user -r /tmp/requirements.txt

RUN pip3 install --user torch tensorflow ray[rllib,tune] sb3_contrib polars plotnine numpy

